#!/bin/bash
source .env || true

cd "${CA_INPUT_FOLDER}"
FOLDERS=$(find . -maxdepth 1 -type d -not -path '*/\.*' -exec basename {} \; | tail -n +2)
for FOLDER in $FOLDERS; do
    if [[ -d $FOLDER ]]; then
        cat <<EOF >> ./../.gitlab-ci-generated.yml
build:publish:${FOLDER}:
    <<: *build_publish
    variables:
        PKI_NAME: "${FOLDER}"

EOF
    fi
done
